// src/app/search/search.component.ts
/*
 * Copyright 2018-present Sonatype, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, Input, OnInit } from '@angular/core';
import { SearchService } from "./search.service";
import 'rxjs/add/operator/startWith';
import 'rxjs/add/observable/merge';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/observable/fromEvent';
import { NotificationService } from "../shared/notifications/notification.service";
import { Router } from "@angular/router";
import { BehaviorSubject } from "rxjs/BehaviorSubject";
import { FormControl } from "@angular/forms";
import { SearchDoc } from "./api/search-doc";
import { SearchSuggestion } from "./api/search-suggestion";
import { SearchResult } from "./api/search-result";

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {

  searchDocs: BehaviorSubject<SearchDoc[]> = new BehaviorSubject<SearchDoc[]>([]);

  stateCtrl: FormControl;

  @Input()
  startQuery: string;

  query: string;

  constructor(private searchService: SearchService,
              private router: Router,
              private notificationService: NotificationService) {
  }

  ngOnInit() {
    this.stateCtrl = new FormControl();
    this.stateCtrl.valueChanges.subscribe(s => this.search(s));
    this.stateCtrl.setValue(this.startQuery);
  }

  navigate() {
    if (this.query) {
      this.router.navigate(['/search'], {queryParams: {q: this.query}});
      this.clearSearchResults();
    }
  }

  clearQuery() {
    this.stateCtrl.setValue('');
    this.clearSearchResults();
  }

  private search(query: string) {
    this.query = query;

    if (this.query) {
      this.searchService
        .search(this.query, 0)
        .subscribe(
          searchResult => this.handleSearchResults(searchResult),
          error => this.handleError(error))
    } else {
      this.clearSearchResults();
    }
  }

  private searchSuggestion(suggestion: SearchSuggestion) {
    if (suggestion.suggestionResponse) {
      this.searchService
        .search(suggestion.suggestionResponse.suggestion[0], 0)
        .subscribe(
          searchResult => {
            this.searchDocs.next(searchResult.response.docs)
          },
          error => this.handleError(error));
    }
  }

  private handleSearchResults(searchResult: SearchResult) {
    if (searchResult.response.docs.length) {
      this.searchDocs.next(searchResult.response.docs);
    } else if (searchResult.spellcheck.suggestion) {
      this.searchSuggestion(searchResult.spellcheck.suggestion);
    } else {
      this.clearSearchResults();
    }
  }

  private clearSearchResults() {
    this.searchDocs.next([]);
  }

  private handleError(error) {

    // For "know" exceptions, don't notify users
    if (error.status == 400 &&
      (error.error.includes('org.apache.lucene.queryParser.ParseException') ||
      error.error.includes('400, msg: missing query string'))) {
      return;
    } else if (error.status == 500 && (error.statusText.includes('IllegalArgumentException'))) {
      return;
    }

    this.notificationService.notifySystemUnavailable();
  }
}

<div class="search">
  <div class="search-form" [ngClass]="{'search-mode' : dataSource.hasSearched}">
    <mat-form-field>
      <input matInput #q placeholder="Search" class="">
      <mat-icon matSuffix color="primary">search</mat-icon>
    </mat-form-field>
  </div>

  <div class="search-result" [ngClass]="{'hidden' : !dataSource.totalCount}">

    <mat-table #table [dataSource]="dataSource">

      <ng-container matColumnDef="groupId">
        <mat-header-cell *matHeaderCellDef>
          {{'search.header.groupId' | translate}}
        </mat-header-cell>
        <mat-cell *matCellDef="let row" class="ellipsis">
          <a [routerLink]="['/search/g', row.g]">{{ row.id }}</a>
        </mat-cell>
      </ng-container>

      <ng-container matColumnDef="artifactId">
        <mat-header-cell *matHeaderCellDef class="xs-hide">
          {{'search.header.artifactId' | translate}}
        </mat-header-cell>
        <mat-cell *matCellDef="let row" class="ellipsis xs-hide">
          <a [routerLink]="['/search/a', row.a]">{{row.a}}</a>
        </mat-cell>
      </ng-container>

      <ng-container matColumnDef="latestVersion">
        <mat-header-cell *matHeaderCellDef class="xs-hide">
          {{'search.header.latestVersion' | translate}}
        </mat-header-cell>
        <mat-cell *matCellDef="let row" class="ellipsis xs-hide">
          <a [routerLink]="['/artifact', row.g, row.a, row.latestVersion, row.p]">{{row.latestVersion}}</a>
        </mat-cell>
      </ng-container>

      <ng-container matColumnDef="updated">
        <mat-header-cell *matHeaderCellDef class="sm-hide">
          {{'search.header.updated' | translate}}
        </mat-header-cell>
        <mat-cell *matCellDef="let row" class="ellipsis sm-hide">
          {{row.timestamp | date : format : timezone}}
        </mat-cell>
      </ng-container>

      <ng-container matColumnDef="download">
        <mat-header-cell *matHeaderCellDef class="sm-hide">
          {{'search.header.download' | translate}}
        </mat-header-cell>
        <mat-cell *matCellDef="let row" class="ellipsis sm-hide">
          <span *ngFor="let ec of row.ec">
            <a [routerLink]="['/remotecontent', row.g, row.a, row.latestVersion, row.a + '-' + row.latestVersion + ec]">{{ ec }}</a>
          </span>
        </mat-cell>
      </ng-container>

      <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
      <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>

    </mat-table>

    <mat-paginator #paginator
                   [length]="dataSource.totalCount"
                   [pageIndex]="0"
                   [pageSize]="20">
    </mat-paginator>

  </div>

  <div *ngIf="dataSource.totalCount == 0  && dataSource.hasSearched">
    <h3>{{'search.result.none' | translate}}</h3>
  </div>
</div>

// src/Search/Search.tsx
/*
 * Copyright (c) 2021-present Sonatype, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import React from 'react';
import { NxH1 } from '@sonatype/react-shared-components';
import logo from './center-image.jpeg';

const Search = () => {
  return (
    <React.Fragment>
      <NxH1>Search</NxH1>
      <img src={logo} alt="Logo" />
    </React.Fragment>
  );
};

export default Search;
