// src/app/stats/stats.component.ts
/*
 * Copyright 2018-present Sonatype, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, OnInit } from '@angular/core';
import { StatsService } from "./stats.service";
import { Stat } from "./api/stat";
import { NotificationService } from "../shared/notifications/notification.service";

@Component({
  selector: 'app-stats',
  templateUrl: './stats.component.html',
  styleUrls: ['./stats.component.scss']
})
export class StatsComponent implements OnInit {

  stat: Stat;

  constructor(private statsService: StatsService,
              private notificationService: NotificationService) {
  }

  ngOnInit() {
    this.statsService.stats().subscribe(
      (stat: Stat) => this.stat = stat,
      error => this.notificationService.notifySystemUnavailable());
  }

}

<!--

 Copyright 2018-present Sonatype, Inc.
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

-->

<div class="stats">

  <h3 class="ellipsis">{{ 'stats.title' | translate}}</h3>

  <mat-card class="mat-smo-default-card stats-card" *ngIf="stat">

    <mat-card-header>
      <div mat-card-avatar class="stats-header-image">
        <mat-icon>check_circle</mat-icon>
      </div>
      <mat-card-title>{{ 'stats.status' | translate }}</mat-card-title>
      <mat-card-subtitle>{{ 'stats.optimal' | translate }}</mat-card-subtitle>
    </mat-card-header>

    <mat-card-content>
      <div class="label-value-table">
        <div class="label-column">
          <div class="ellipsis">{{ 'stats.modifiedDate' | translate }}</div>
          <div class="ellipsis">{{ 'stats.gav' | translate }}</div>
          <div class="ellipsis">{{ 'stats.ga' | translate }}</div>
          <div class="ellipsis">{{ 'stats.repoSize' | translate }}</div>
        </div>
        <div class="value-column">
          <div>{{ stat?.dateModified }}</div>
          <div>{{ stat?.gavNumber }}</div>
          <div>{{ stat?.gaNumber }}</div>
          <div>{{ stat?.repoSize }} {{ 'stats.repoSizeUnit' | translate}}</div>
        </div>
      </div>
    </mat-card-content>

  </mat-card>

  <mat-card class="stats-card" *ngIf="!stat">

    <mat-card-header>
      <div mat-card-avatar class="stats-header-image warning">
        <mat-icon>warning</mat-icon>
      </div>
      <mat-card-title>{{ 'stats.status' | translate }}</mat-card-title>
      <mat-card-subtitle>{{ 'smo.unavailable' | translate }}</mat-card-subtitle>
    </mat-card-header>

  </mat-card>

</div>

// src/components/Stats/Stats.tsx
/*
 * Copyright (c) 2021-present Sonatype, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import React from 'react';
import { NxH1 } from '@sonatype/react-shared-components';

const Stats = () => {
  return <NxH1>Stats</NxH1>;
};

export default Stats;
